### ISSUE TITLE
Paired recordings reports page

### ISSUE THREAD

**Issue by mayofaulkner** [int-brain-lab/iblalyx#41]
Add paired recordings page to ibl_reports on alyx

- [x] Integrate d3 images
- [x] Write alyx view to generate json
- [x] Callbacks for project, qc, regions(?)
- [x] Filter for qcs
- [x] Test out iblatlas installation
- [x] Deploy
- [x] Cronjob for new paired_experiments.pqt file

**Comment by oliche** [comment]
`./manage.py ibl paired_recordings` generates tables on s3://alyx-uploaded/uploaded/paired_experiments.pqt and runs every Saturday morning on mbox
