### ISSUE TITLE
Remove dud sessions from alyx

### ISSUE THREAD

**Issue by mayofaulkner** [int-brain-lab/iblalyx#61]
In many cases there are dud sessions for a single experiment. Write a script that will go through alyx and remove any old sessions that do not have any tasks or datasets associated with it. 
Need to make sure there is no session narrative/ water / weighing associated with the sessions before deleting

**Comment by oliche** [comment]
Done on cortexlab and on main alyx.

Script:
https://github.com/int-brain-lab/ibldevtools/blob/9c7df7f08bfb4796b914af94dd79e5b882858fef/olivier/2024-04-10_remove_dud_sessions_alyx.py#L13-L12
