### ISSUE TITLE
Release trials table for behavior paper subjects

### ISSUE THREAD

**Issue by mayofaulkner** [int-brain-lab/iblalyx#69]
Linked to this neurostars item (https://neurostars.org/t/accessing-training-status-through-public-database/29648/3). Discuss whether we should release the subject trials table for BWM and behavior papers subjects

**Comment by k1o0** [comment]
Clarify Anne's position in IBL wrt data use and authorship plans.

**Comment by oliche** [comment]
No further need for it.
